article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('', views.article_list, name='article_list'),
    path('<int:id>/', views.article_detail, name='article_detail'),
    path('article_create/', views.article_create, name='article_create'),
    path(
        'article_safe_delete/<int:id>/',
        views.article_safe_delete,
        name="article_safe_delete"
        ),
    path('article_update/<int:id>/', views.article_update, name="article_update"),

    # path('list_view/', views.ArticleListView.as_view(), name='list_view'),

]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">

<head>
    <meta charset="utf-8">
    <!-- 预留标题的位置 -->
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <style media="screen">
        {% block addstyle %}{% endblock addstyle %}
    </style>
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <br><br><br>
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.15.0/popper.js"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/layer/2.3/layer.js"></script>
</body>

</html>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->

<div>
    <br><br><br>
</div>

<footer class="py-2 bg-dark fixed-bottom">
    <div class="container-fluid">
        <p class="m-0 text-center text-white">fuko</p>
    </div>
</footer>

templates/header.html
<!-- 定义导航栏 -->
{% load staticfiles %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <!-- <img src="{% static 'iamges\fuko.jpg' %}" alt="Logo" style="width:30px; height:30px;"> -->
      <a class="navbar-brand" href="/article/">fukodes</a>

      <div>
        <ul class="navbar-nav">
          <!-- 条目 -->
          {% if user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'article:article_create' %}">随笔</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="/article/">文章</a>
          </li>

          {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>个人信息</a>
                <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>

              </div>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {%if user.is_authenticated %}
  <form
      style="display: none;"
      id="user_delete"
      action="{% url 'userprofile:delete' user.id %}"
      method="POST"
  >
  {% csrf_token %}
      <button type="submit">发送</button>
  </form>
  <script>
    function user_delete() {
      layer.open({
        title: "确认删除",
        content: "确认删除用户资料吗？",
        yes: function(index, layero) {
          $('form#user_delete button').click();
          layer.close(index);
        },
      })
    }
  </script>
  {% endif %}