article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('', views.article_list, name='article_list'),
    path('<int:id>/', views.article_detail, name='article_detail'),
    path('article_create/', views.article_create, name='article_create'),
    path(
        'article_safe_delete/<int:id>/',
        views.article_safe_delete,
        name="article_safe_delete"
        ),
    path('article_update/<int:id>/', views.article_update, name="article_update"),

    # path('list_view/', views.ArticleListView.as_view(), name='list_view'),

]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    path('comment_list/<int:article_id>/', views.comment_list, name='comment_list'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

article/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.utils import timezone
from PIL import Image
# Create your models here.


class ArticleColumn(models.Model):
    title = models.CharField(max_length=100, blank=True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    # 文章更新时间。参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)
    total_views = models.PositiveIntegerField(default=0)
    tags = TaggableManager(blank=True)
    avatar = models.ImageField(upload_to='article/%Y%m%d/', blank=True)
    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

    def save(self, *args, **kwargs):
        article = super(ArticlePost, self).save(*args, **kwargs)

        if self.avatar and not kwargs.get('update_fields'):
            image = Image.open(self.avatar)
            (x, y) = image.size
            new_x = 300
            new_y = 200
            resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)
            resized_image.save(self.avatar.path)

        return article

article/forms.py
from django import forms
from .models import ArticlePost

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title', 'body', 'tags', 'avatar')

article/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.views.generic import ListView
from .models import ArticlePost, ArticleColumn
from .forms import ArticlePostForm
from comment.models import Comment


import markdown
# Create your views here.


# class ArticleListView(ListView):
#     context_object_name = 'articles'
#     template_name = 'article/list.html'
#     paginate_by = 3
#
#     def get_queryset(self):
#         queryset = ArticlePost.objects.all()
#
#         return queryset
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['order'] = 'total_views'
#         return context


def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')

    article_list = ArticlePost.objects.all()
    if search:
        article_list = article_list.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        search = ''

    if column is not None and column.isdigit():
        article_list = article_list.filter(column=column)

    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])

    if order == 'total_views':
        article_list = article_list.order_by('-total_views')

    paginator = Paginator(article_list, 10)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.toc',
        ])
    for art in articles:
        art.body = md.convert(art.body)

    context = {
        'articles': articles,
        'order': order,
        'search': search,
        'column': column,
        'tag': tag,
    }
    return render(request, 'article/list.html', context)

def article_detail(request, id):
    article = ArticlePost.objects.get(id=id)
    comments = Comment.objects.filter(article=id)

    article.total_views += 1
    article.save(update_fields=['total_views'])
    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
    article.body = md.convert(article.body)

    context = {'article': article, 'comments': comments, 'toc': md.toc}
    return render(request, 'article/detail.html', context)

@login_required(login_url='/userprofile/login/')
def article_create(request):
    if not request.user.is_superuser:
        return HttpResponse("无权限")
    if request.method == 'POST':
        article_post_form = ArticlePostForm(request.POST, request.FILES)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            new_article.save()
            article_post_form.save_m2m()
            return redirect("/article/")
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    else:
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context = {'article_post_form': article_post_form, 'columns':columns}
        return render(request, 'article/create.html', context)

@login_required(login_url='/userprofile/login/')
def article_safe_delete(request, id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        if article.author_id == request.user.id:
            article.delete()
            return redirect("/article/")
        else:
            return HttpResponse("无权限")
    else:
        return HttpResponse("仅允许post请求")

@login_required(login_url='/userprofile/login/')
def article_update(request, id):
    article = ArticlePost.objects.get(id=id)
    if article.author_id == request.user.id:
        if request.method == 'POST':
            article_post_form = ArticlePostForm(data=request.POST)
            if article_post_form.is_valid():
                article.title = request.POST['title']
                article.body = request.POST['body']
                if request.POST['column'] != 'none':
                    article.column = ArticleColumn.objects.get(id=request.POST['column'])
                else:
                    article.column = None
                article.save()
                return redirect("article:article_detail", id=id)
            else:
                return HttpResponse("表单内容有误，请重新填写。")
        else:
            article_post_form = ArticlePostForm(),
            columns = ArticleColumn.objects.all()
            context = {'article': article, 'article_post_form': article_post_form, 'columns': columns}
            return render(request, 'article/update.html', context)
    else:
        return HttpResponse("无权限")

templates/article/create.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} 写文章 {% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="POST" action="." enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章标题图 -->
                <div class="form-group">
                    <label for="avatar">标题图</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>
                <div class="form-gtoup">
                    <label for="column">栏目</label>
                    <select class="form-control" id="column" name="column">
                        <option value="none">选择栏目...</option>
                        {% for column in columns %}
                        <option value="{{ column.id }}">{{ column }}</option>
                        {% endfor %}
                    </select>
                </div>
                <!-- 文章标签 -->
                <div class="form-group">
                    <label for="tags">标签</label>
                    <input type="text"
                           class="form-control col-3"
                           id="tags"
                           name="tags"
                    >
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>

                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    文章详情
{% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-9">
            <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
            <div class="col-12 alert alert-info">
                作者：{{ article.author }}
                {% if article.author_id == request.user.id %}
                    <a class="mr-3 float-right text-danger" onclick="confirm_safe_delete()">删除文章</a>
                    <form
                        style="display: none;"
                        id="safe_delete"
                        action="{% url 'article:article_safe_delete' article.id %}"
                        method="POST"
                        >
                        {% csrf_token %}
                        <button type="submit">发送</button>
                    </form>
                    <a href="{% url 'article:article_update' article.id %}" class="mr-3 float-right">编辑文章</a>
                {% endif %}
                <div>
                    浏览：{{ article.total_views }}
                </div>
                <span>
                    {% for tag in article.tags.all %}
                        <a href="#" class="badge badge-secondary">{{ tag }}</a>
                    {% endfor %}
                </span>
            </div>
            <div class="col-12"><p>{{ article.body|safe }}</p></div>

            <hr>
            {% if user.is_authenticated %}
                <div>
                    <form
                        action="{% url 'comment:comment_list' article.id %}"
                        method="post"
                        >
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="body"><strong>发言/意见:</strong></label>
                            <textarea name="body" rows="4" cols="80"
                                    class="form-control" id='body'
                            ></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">发送</button>
                    </form>
                </div>
            {% else %}
                <br>
                <h5 class="row justify-content-center">
                    请<a href="{% url 'userprofile:login' %}">登录</a>后回复
                </h5>
            {% endif %}
                <br>
                <h4>共有{{ comments.count }}条评论</h4>
                <div>
                    {% for comment in comments %}
                    <hr>
                    <p>
                        <strong>
                            {{ comment.user }}
                        </strong> &nbsp;&nbsp;
                        <span style="color: gray">
                            {{ comment.created|date:"Y-m-d" }}
                        </span>:
                    </p>
                    <pre style="font-family: inherit; font-size: 1em">{{ comment.body }}</pre>
                {% endfor %}
            </div>

        </div>

        <div class="col-3 mt-4">
            <h4><strong>目录</strong></h4>
            <hr>
            <div>
                {{ toc|safe }}
            </div>
        </div>
    </div>

</div>

<script>
    function confirm_safe_delete() {
        layer.open({
            title: "确认删除",
            content: "确认删除这篇文章吗？",
            yes: function(index, layero) {
                $('form#safe_delete button').click();
                layer.close(index);
            },
        })
    }
</script>

{% endblock content %}

templates/article/list.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

{% block addstyle %}
#art_style a {
    text-decoration: none;
}
#abstract p {
    font-style: normal;
    font-size: 15px;
}
{% endblock addstyle %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 定义放置文章标题的div容器 -->
<div class="container">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb d-inline-flax" id='bc'>
            <li class="breadcrumb-item mt-3" id="latest_art" onclick="breaditem_show('latest_art')">
                <a href="{% url 'article:article_list' %}?search={{ search }}&column={{ column }}&tag={{ tag }}">最新</a>
            </li>
            <li class="breadcrumb-item mt-3" id="hot_art" onclick="breaditem_show('hot_art')">
                <a href="{% url 'article:article_list' %}?order=total_views&search={{ search }}&column={{ column }}&tag={{ tag }}">热门</a>
            </li>
            <li class="ml-auto mt-2">
                <form class="form-inline">
                    <label class="sr-only">content</label>
                    <input type="text"
                        class="form-control mb-2 mr-sm-2"
                        name="search"
                        placeholder="搜索文章"
                        required
                        >
                </form>
            </li>
        </ol>
    </nav>

    {% if search %}
        {% if articles %}
            <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
            <hr>
        {% else %}
            <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
            <hr>
        {% endif %}
    {% endif %}
    <!-- 文章内容 -->
    {% for article in articles %}
    <div class="row mt-2">
        <!-- NOTE: image of title -->
        {% if article.avatar %}
            <div class="col3">
                <img src="{{ article.avatar.url }}" alt="avatar"
                    style="max-width:100%; border-radius: 20px;">
            </div>
        {% endif %}
        <div class="col-12" id="art_style">
            {% if article.column %}
                <a type="button"
                    href="{% url 'article:article_list' %}?order={{ order }}&search={{ search }}&column={{ article.column_id }}&tag={{ tag }}"
                    class="btn btn-sm mb-2
                        {% if article.column.title == 'Django' %}
                            btn-success
                        {% elif article.column.title == 'Python' %}
                           btn-danger
                        {% elif article.column.title == 'HTML' %}
                           btn-warning
                        {% endif %}
                        "
                >{{ article.column }}</a>
            {% endif %}
            <!-- tags -->
            <span>
                {% for tag in article.tags.all %}
                    <a href="/article/?order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}" class="badge badge-secondary">{{ tag }}</a>
                {% endfor %}
            </span>
            <!-- 标题 -->
            <h4>
                <b>
                    <a href="{% url 'article:article_detail' article.id %}"
                        style="color: black;"
                    >{{ article.title }}</a>
                </b>
            </h4>
            <!-- 摘要 -->
            <div id='abstract'>
                <p style="color: gray;">
                    {{ article.body|safe|slice:'100' }}...
                </p>
            </div>
            <!-- 注脚 -->
            <p>
                <span style="color: blue;">
                    {{ article.created|date:'Y-m-d'}}发布&nbsp;&nbsp;&nbsp;
                </span>
                <span style="color: darkred;">
                    {{ article.updated|date:'Y-m-d' }}更新&nbsp;&nbsp;&nbsp;
                </span>
                <span style="color: green;">
                    {{ article.total_views }}浏览
                </span>
            </p>
        </div>
    </div>
    <hr style="width=100%;">
    {% endfor %}

    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                {% if articles.has_previous %}
                    <a href="?page=1&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}" class="btn btn-primary">&laquo; 1</a>
                    {% if articles.previous_page_number != 1 %}
                    <span>...</span>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}" class="btn btn-secondary">
                        {{ articles.previous_page_number }}
                    </a>
                    {% endif %}
                {% endif %}
                <span class="current btn btn-info btn-lg">{{ articles.number }}</span>
                {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}" class="btn btn-secondary">
                        {{ articles.next_page_number }}
                    </a>
                    {% if articles.paginator.num_pages != articles.next_page_number %}
                        <span>...</span>
                        <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}" class="btn btn-primary">
                            &raquo; {{ articles.paginator.num_pages }}
                        </a>
                    {% endif %}
                {% endif %}
            </span>
        </div>
    </div>

</div>
{% endblock content %}

templates/article/update.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="POST" action='.'>
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <div class="form-gtoup">
                    <label for="column">栏目</label>
                    <select class="form-control" id="column" name="column">
                        <option value="none">选择栏目...</option>
                        {% for column in columns %}
                        <option value="{{ column.id }}"
                            {% if column.id == article.column.id %}
                                selected
                            {% endif %}
                        >{{ column }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}